services:
  db:
    image: mysql:8.0
    container_name: ols-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chethai_db
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  be:
    build:
      context: ./be
    container_name: ols-be
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chethai_db?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_ALLOWED_ORIGIN: http://localhost:4173,https://tea.truong.cloud,http://localhost:5173,https://chat.truong.cloud
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  agent:
    build:
      context: ./agent
    container_name: ols-agent
    environment:
      API_URL: http://be:8080/api/v1
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3001:3001"
    depends_on:
      - be

  fe:
    build:
      context: ./fe
    container_name: ols-fe
    ports:
      - "4173:4173"
    depends_on:
      - agent
